"""EX06 - Choose Your Own Adventure."""

__author__ = "730469023"

import random

points: int = 0
smiley_face: str = "/U0001F603"
sad_face: str = "/U0001F622"


def greet() -> None:
    """Function to greet player and assign their name"""
    global player
    print("Greetings Player! This is a number guessing game, where a random number will be generated by the system and the primary objective it to simply guess it in the least number of tries as possible.")
    player = str(input("Around these lands, what would you like to be called?: "))


def main() -> bool:
    """Main Game Function"""
    greet()
    global points
    random_num: int = random.randint(1, 10)
    count: int = 1
    guess: int = input(f"Hello {player}! What would you like your guess #1 to be? (Keep in mind the possible range is from 1-10, inclusive of both 1 and 10 :) ->  ")
    while guess != random_num:
        guess: int = input(f"Hello {player}! What would you like your guess #{count} to be? (Keep in mind the possible range is from 1-10, inclusive of both 1 and 10 :) ->  ")
        count += 1
        points += 1
        print(f"You now have {points} points.")
        if guess > random_num:
            print("Incorrect unfortunately. Your guess was too high!")
        if guess < random_num:
            print("Incorrect unfortunately. Your guess was too low!")
    else:
        print(f"WOO WOO. You got it in {count} tries my friend.")
        points += 10
        print(f"You now have {points} points! Congrats on guessing the number and hitting the jackpot!")
        continue_game = input(f"Greetings again {player}. To win this game, you need 50 points. You are currently at {points} points. Would you like to continue? (Type Yes to Continue, No to Quit) ")
    if continue_game == "Yes":
        main()
    else:
        print(f"Sounds good, your total number of points is: {points}")
        if points >= 50:
            print("You win the entire game! Congratulations! " + smiley_face)
            return True
        else:
            print("Unfortunately you didnt get 50 points. I'm sorry. Better luck next time. " + sad_face)
            return False


if __name__ == "__main__":
    main()